<a href="https://colab.research.google.com/github/thisisgsn-cpu/northstar-analytics-project/blob/main/notebooks/01_sql_in_r.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
install.packages("sqldf")
install.packages("dplyr")
install.packages("ggplot2")

library(sqldf)
library(dplyr)
library(ggplot2)

cat("All required libraries loaded successfully")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

All required libraries loaded successfully

In [ ]:
system("git clone https://github.com/thisisgsn-cpu/northstar-analytics-project.git")

In [ ]:
orders <- read.csv("/content/northstar-analytics-project/data/orders.csv")
deliveries <- read.csv("/content/northstar-analytics-project/data/deliveries.csv")
customers <- read.csv("/content/northstar-analytics-project/data/customers.csv")
drivers <- read.csv("/content/northstar-analytics-project/data/drivers.csv")
vehicles <- read.csv("/content/northstar-analytics-project/data/vehicles.csv")
hubs <- read.csv("/content/northstar-analytics-project/data/hubs.csv")
incidents <- read.csv("/content/northstar-analytics-project/data/incidents.csv")
complaints <- read.csv("/content/northstar-analytics-project/data/complaints.csv")
app_events <- read.csv("/content/northstar-analytics-project/data/app_events.csv")

cat("All datasets loaded successfully")

All datasets loaded successfully

In [ ]:
head(orders)
head(deliveries)
head(customers)

str(orders)
str(deliveries)

dim(orders)
dim(deliveries)

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
6 O00006   C0437       Retail       2024-08-05 04:55:00  1
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       AIRPORT      Low            109.30      App
3 West        AIRPORT      High            33.50      Phone
4 RiverSide   North        Medium          10.04      App
5 Riverside   SOUTH        Low            125.58      Phone
6 CENTRAL     East         High           151.44      Web
  special_handling_flag
1 0
2 0
3 0
4 1
5 0
6 1

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
6 2024-09-12 17:11:52.384869 Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

  customer_id age home_zone customer_type signup_date         loyalty_score
1 C0001       26  North     SME           2024-11-27 04:25:00 44.9
2 C0002       61  AIRPORT   Consumer      2025-10-28 01:04:00 55.4
3 C0003       66  East      Consumer      2025-07-02 03:23:00 75.9
4 C0004       75  CENTRAL   Consumer      2025-08-19 01:58:00 32.5
5 C0005       26  Riverside Consumer      2025-06-03 06:02:00 55.9
6 C0006       41  WEST      Consumer      2024-03-29 13:26:00 39.9
  app_engagement_score preferred_channel account_status
1  69.2                App               Active
2  66.6                App               Active
3  33.8                                  Active
4  33.0                App               Active
5 100.0                Web               Active
6  43.3                Web               Active

'data.frame':	1250 obs. of  11 variables:
 $ order_id             : chr  "O00001" "O00002" "O00003" "O00004" ...
 $ customer_id          : chr  "C0292" "C0459" "C0161" "C0520" ...
 $ service_type         : chr  "Passenger" "Passenger" "Passenger" "Parcel" ...
 $ order_created_at     : chr  "2024-08-20 14:43:00" "2024-05-14 22:16:00" "2025-09-02 14:37:00" "2025-01-11 17:15:00" ...
 $ promised_window_hours: int  6 24 4 2 12 1 2 4 12 6 ...
 $ pickup_zone          : chr  "Airport" "North" "West" "RiverSide" ...
 $ dropoff_zone         : chr  "South" "AIRPORT" "AIRPORT" "North" ...
 $ priority_level       : chr  "Medium" "Low" "High" "Medium" ...
 $ order_value          : num  126.7 109.3 33.5 10 125.6 ...
 $ booking_channel      : chr  "App" "App" "Phone" "App" ...
 $ special_handling_flag: int  0 0 0 1 0 1 0 0 0 0 ...
'data.frame':	950 obs. of  13 variables:
 $ delivery_id                  : chr  "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr  "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr  "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr  "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr  "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : chr  "2024-06-18 10:57:00" "2025-01-11 18:45:00" "2025-06-02 20:39:00" "2024-03-08 23:31:00" ...
 $ delivery_completed_at        : chr  "2024-06-19 09:05:59.904311" "2025-01-11 17:39:00.000000" "2025-06-02 21:45:32.366770" "2024-03-09 23:30:08.103702" ...
 $ delivery_status              : chr  "Failed" "OnTime" "OnTime" "Delayed" ...
 $ route_distance_km            : num  17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : int  1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num  3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num  12.05 13.41 8.51 13.62 9.22 ...

[1] 1250   11

[1] 950  13

In [ ]:
hub_failure_analysis <- sqldf("

SELECT

    h.hub_name,
    h.zone,

    COUNT(d.delivery_id) AS total_deliveries,

    SUM(
        CASE
            WHEN d.delivery_status = 'Failed'
            THEN 1
            ELSE 0
        END
    ) AS failed_deliveries,

    SUM(
        CASE
            WHEN d.delivery_status = 'OnTime'
            THEN 1
            ELSE 0
        END
    ) AS successful_deliveries,

    ROUND(
        (
            SUM(
                CASE
                    WHEN d.delivery_status = 'Failed'
                    THEN 1
                    ELSE 0
                END
            ) * 100.0
        ) / COUNT(d.delivery_id),
        2
    ) AS failure_rate

FROM deliveries d

INNER JOIN hubs h
ON d.hub_id = h.hub_id

GROUP BY h.hub_name, h.zone

ORDER BY failure_rate DESC

")

hub_failure_analysis

  hub_name       zone      total_deliveries failed_deliveries
1 Midtown Relay  Central   128              26
2 Central Core   Central   115              23
3 Airport Hub    Airport   104              15
4 West Gate      West      127              16
5 North Exchange North     136              17
6 Riverside Hub  Riverside 115              14
7 South Link     South     106              10
8 East Dock      East      119              11
  successful_deliveries failure_rate
1 80                    20.31
2 67                    20.00
3 62                    14.42
4 83                    12.60
5 93                    12.50
6 76                    12.17
7 70                     9.43
8 85                     9.24

In [ ]:
driver_route_analysis <- sqldf("

SELECT

    dr.driver_id,
    dr.base_zone,
    dr.employment_type,

    COUNT(d.delivery_id) AS total_deliveries,

    ROUND(
        AVG(d.manual_route_override_count),
        2
    ) AS average_route_overrides,

    ROUND(
        AVG(d.customer_rating_post_delivery),
        2
    ) AS average_customer_rating,

    ROUND(
        AVG(d.route_distance_km),
        2
    ) AS average_route_distance,

    ROUND(
        AVG(dr.driver_rating),
        2
    ) AS driver_performance_rating

FROM deliveries d

INNER JOIN drivers dr
ON d.driver_id = dr.driver_id

GROUP BY
    dr.driver_id,
    dr.base_zone,
    dr.employment_type

HAVING total_deliveries >= 3

ORDER BY
    average_route_overrides DESC,
    average_customer_rating ASC

")

driver_route_analysis

    driver_id base_zone employment_type total_deliveries
1   D127      CENTRAL   FullTime         6
2   D124      north     FullTime         4
3   D085      North     PartTime         4
4   D130      WEST      FullTime         8
5   D062      South     FullTime         3
6   D069      NORTH     PartTime         7
7   D139      South     FullTime         5
8   D105      RiverSide Contract         7
9   D028      North     FullTime         7
10  D027      AIRPORT   PartTime         6
11  D143      CENTRAL   FullTime         5
12  D136      Airport   FullTime         4
13  D107      RiverSide FullTime         4
14  D003      AIRPORT   FullTime         4
15  D104      WEST      FullTime         7
16  D131      SOUTH     FullTime         9
17  D042      North     FullTime         3
18  D090      NORTH     FullTime         6
19  D114      Ctr       FullTime         3
20  D073      East      FullTime         5
21  D033      South     PartTime         7
22  D103      Central   FullTime         4
23  D008      SOUTH     FullTime         8
24  D030      CENTRAL   FullTime         7
25  D098      SOUTH     Contract         5
26  D108      South     FullTime        11
27  D165      North     PartTime         6
28  D074      Central   FullTime         6
29  D087      north     Contract        12
30  D046      South     FullTime         6
⋮   ⋮         ⋮         ⋮               ⋮
122 D116      CENTRAL   FullTime         7
123 D123      RiverSide FullTime         7
124 D097      West      FullTime         7
125 D092      East      FullTime         5
126 D156      South     FullTime         5
127 D101      WEST      FullTime         5
128 D049      CENTRAL   Contract        10
129 D157      South     FullTime         5
130 D037      north     PartTime         8
131 D102      East      PartTime        13
132 D164      Central   FullTime         8
133 D063      north     PartTime         3
134 D140      North     FullTime         3
135 D034      West      FullTime         6
136 D023      EAST      FullTime         6
137 D093      South     PartTime         6
138 D045      NORTH     FullTime         9
139 D015      East      FullTime         6
140 D018      WEST      PartTime         7
141 D155      CENTRAL   PartTime         7
142 D128      Central   Contract         4
143 D058      AIRPORT   FullTime         4
144 D064      SOUTH     PartTime         4
145 D167      SOUTH     PartTime         4
146 D014      NORTH     FullTime         4
147 D061      RiverSide Contract         4
148 D091      Riverside FullTime         6
149 D071      CENTRAL   PartTime         7
150 D109      Central   Contract         4
151 D025      North     FullTime         3
    average_route_overrides average_customer_rating average_route_distance
1   2.83                    4.10                     8.38
2   2.00                    3.41                    20.73
3   2.00                    3.42                    17.95
4   2.00                    3.80                    17.28
5   2.00                    3.82                    19.63
6   2.00                    3.94                    19.17
7   2.00                    4.08                    12.23
8   2.00                    4.21                    10.23
9   1.86                    3.54                    18.67
10  1.83                    3.64                    17.74
11  1.80                    3.76                    11.72
12  1.75                    3.67                    19.20
13  1.75                    4.13                    23.75
14  1.75                    4.45                    17.01
15  1.71                    3.93                    11.71
16  1.67                    3.66                    14.82
17  1.67                    4.01                    12.49
18  1.67                    4.01                    12.42
19  1.67                    4.25                    10.99
20  1.60                    4.02                    13.04
21  1.57                    3.95                    14.70
22  1.50                    3.28                    10.27
23  1.50                    3.92                    10.27
24  1.43                    4.31                    20.42
25  1.40                    3.59                    10.65
26  1.36                    4.41                    16.85
27  1.33                    2.98                    13.11
28  1.33                    3.73                    13.56
29  1.33                    3.82                    11.37
30  1.33                    4.13                    14.40
⋮   ⋮                       ⋮                       ⋮
122 0.43                    3.65                    14.97
123 0.43                    3.65                    11.92
124 0.43                    3.71                    10.94
125 0.40                    3.38                    10.75
126 0.40                    3.55                    14.49
127 0.40                    3.56                    12.22
128 0.40                    3.76                    11.72
129 0.40                    4.16                    13.52
130 0.38                    4.07                    14.13
131 0.38                    4.14                    12.58
132 0.38                    4.34                    11.71
133 0.33                    2.37                     5.99
134 0.33                    3.40                    12.03
135 0.33                    3.88                    11.33
136 0.33                    3.90                    12.05
137 0.33                    4.22                    14.23
138 0.33                    4.25                    16.01
139 0.33                    4.52                    18.60
140 0.29                    3.92                    12.68
141 0.29                    4.20                    17.45
142 0.25                    3.85                     9.41
143 0.25                    4.06                    10.71
144 0.25                    4.23                    14.16
145 0.25                    4.35                    11.83
146 0.25                    4.43                    12.81
147 0.25                    4.61                     7.57
148 0.17                    3.13                    15.46
149 0.14                    3.95                    14.22
150 0.00                    3.52                     8.04
151 0.00                    4.65                    10.06
    driver_performance_rating
1   4.19
2   3.78
3   4.11
4   3.64
5   4.48
6   5.00
7   4.99
8   3.71
9   4.07
10  3.70
11  4.14
12  3.99
13  4.82
14  5.00
15  3.45
16  4.26
17  3.37
18  3.78
19  4.07
20  4.58
21  4.05
22  4.40
23  3.88
24  4.56
25  4.29
26  4.33
27  3.89
28  4.61
29  4.43
30  4.06
⋮   ⋮
122 4.19
123 4.12
124 4.48
125 4.24
126 3.62
127 4.48
128 4.00
129 4.42
130 4.67
131 4.62
132 4.07
133 4.03
134 3.92
135 4.27
136 4.16
137 4.43
138 4.12
139 4.34
140 4.57
141 3.98
142 3.32
143 4.27
144 4.18
145 4.64
146 4.70
147 4.38
148 4.46
149 4.49
150 3.94
151 3.72

In [ ]:
customer_issue_analysis <- sqldf("

SELECT

    c.customer_id,
    c.customer_type,
    c.home_zone,

    COUNT(cp.complaint_id) AS total_complaints,

    SUM(
        CASE
            WHEN d.delivery_status = 'Failed'
            THEN 1
            ELSE 0
        END
    ) AS failed_deliveries,

    ROUND(
        SUM(cp.compensation_amount),
        2
    ) AS total_compensation,

    ROUND(
        AVG(c.loyalty_score),
        2
    ) AS average_loyalty_score,

    COUNT(DISTINCT o.order_id) AS total_orders

FROM customers c

LEFT JOIN complaints cp
ON c.customer_id = cp.customer_id

LEFT JOIN orders o
ON c.customer_id = o.customer_id

LEFT JOIN deliveries d
ON o.order_id = d.order_id

GROUP BY
    c.customer_id,
    c.customer_type,
    c.home_zone

HAVING total_complaints >= 2

ORDER BY
    total_complaints DESC,
    failed_deliveries DESC,
    total_compensation DESC

")

customer_issue_analysis

    customer_id customer_type home_zone total_complaints failed_deliveries
1   C0372       Consumer      West      18               3
2   C0545       Consumer      SOUTH     18               0
3   C0242       Consumer      East      15               0
4   C0368       Consumer      North     12               4
5   C0023       Consumer      South     12               2
6   C0335       SME           NORTH     12               0
7   C0172       Consumer      north     12               0
8   C0622       Consumer      RiverSide 12               0
9   C0599       Consumer      North     12               0
10  C0529       SME           Riverside 10               2
11  C0476       Consumer      NORTH     10               2
12  C0032       Consumer      West      10               2
13  C0361       Consumer      SOUTH     10               0
14  C0573       SME           AIRPORT    9               3
15  C0110       Consumer      EAST       9               3
16  C0421       Consumer      CENTRAL    9               0
17  C0626       Consumer      SOUTH      9               0
18  C0351       Enterprise    CENTRAL    8               2
19  C0597       Consumer      north      8               2
20  C0618       Consumer      Airport    8               2
21  C0480       Enterprise    NORTH      8               2
22  C0054       Consumer      WEST       8               2
23  C0564       Consumer      EAST       8               0
24  C0369       Consumer      West       8               0
25  C0595       Consumer      CENTRAL    8               0
26  C0259       Consumer      Central    8               0
27  C0015       SME           SOUTH      8               0
28  C0378       Consumer      RiverSide  8               0
29  C0157       Consumer      CENTRAL    8               0
30  C0571       Consumer      South      8               0
⋮   ⋮           ⋮             ⋮         ⋮                ⋮
168 C0639       Consumer      East      2                0
169 C0515       Consumer      Riverside 2                0
170 C0562       Consumer      WEST      2                0
171 C0228       SME           north     2                0
172 C0020       SME           North     2                0
173 C0509       Consumer      WEST      2                0
174 C0138       Consumer      SOUTH     2                0
175 C0046       SME           Ctr       2                0
176 C0321       Consumer      South     2                0
177 C0454       Consumer      South     2                0
178 C0426       SME           RiverSide 2                0
179 C0381       Consumer      Ctr       2                0
180 C0074       SME           West      2                0
181 C0256       SME           Ctr       2                0
182 C0161       Consumer      north     2                0
183 C0139       SME           Central   2                0
184 C0100       Consumer      Ctr       2                0
185 C0072       SME           north     2                0
186 C0272       Consumer      north     2                0
187 C0185       Consumer      SOUTH     2                0
188 C0174       Consumer      north     2                0
189 C0070       Consumer      WEST      2                0
190 C0586       Consumer      CENTRAL   2                0
191 C0193       Consumer      South     2                0
192 C0428       SME           Riverside 2                0
193 C0234       Consumer      North     2                0
194 C0206       SME           SOUTH     2                0
195 C0475       Consumer      CENTRAL   2                0
196 C0309       SME           Airport   2                0
197 C0173       Consumer      Riverside 2                0
    total_compensation average_loyalty_score total_orders
1   431.34             26.2                  6
2   441.60             66.9                  6
3   378.75             83.8                  5
4   232.53             49.5                  3
5   265.44             73.1                  6
6   277.32             45.3                  6
7   245.96             75.4                  4
8   109.14             54.2                  6
9    52.44             81.4                  6
10  186.40             43.2                  5
11  147.50             66.0                  5
12  135.30             85.0                  5
13  299.85               NA                  5
14  334.26             57.3                  3
15  132.42               NA                  3
16  356.94             59.0                  3
17  108.69             61.6                  3
18  408.08             48.6                  4
19  208.44             57.2                  4
20  201.28             68.4                  4
21  155.04             67.6                  4
22   49.64             42.4                  4
23  151.72             48.6                  4
24  141.84             47.6                  4
25   99.20             48.3                  4
26   83.00             78.3                  4
27   77.84             54.5                  4
28   65.08             26.2                  4
29   63.08             67.9                  4
30   47.44             44.1                  4
⋮   ⋮                  ⋮                     ⋮
168 40.12              54.4                  2
169 40.08              74.0                  2
170 38.96              47.9                  2
171 38.48              51.0                  2
172 36.74              55.5                  2
173 32.34                NA                  2
174 29.43              93.2                  1
175 28.12              84.8                  2
176 26.92              99.0                  2
177 25.94              62.2                  2
178 21.88              49.0                  2
179 21.06              74.4                  2
180 20.64              41.6                  2
181 17.70              45.7                  2
182 17.32              87.1                  2
183 16.38              51.7                  2
184 14.98              28.0                  1
185 14.98              48.2                  2
186 14.85              52.2                  1
187 14.18              77.5                  2
188 11.40              93.5                  2
189  8.18              77.1                  2
190  6.32              87.4                  2
191  1.86              84.0                  2
192  0.00              52.9                  2
193  0.00              54.1                  2
194  0.00              50.3                  2
195    NA              81.9                  2
196    NA              29.0                  2
197    NA              78.5                  2

In [ ]:
vehicle_maintenance_analysis <- sqldf("

SELECT

    v.vehicle_id,
    v.vehicle_type,
    v.assigned_zone,
    v.maintenance_status,

    ROUND(
        AVG(v.battery_health_pct),
        2
    ) AS average_battery_health,

    ROUND(
        AVG(v.odometer_km),
        2
    ) AS average_odometer_km,

    COUNT(d.delivery_id) AS total_deliveries,

    SUM(
        CASE
            WHEN d.delivery_status = 'Failed'
            THEN 1
            ELSE 0
        END
    ) AS failed_deliveries,

    ROUND(
        AVG(d.fuel_or_charge_cost),
        2
    ) AS average_operational_cost,

    ROUND(
        AVG(d.customer_rating_post_delivery),
        2
    ) AS average_customer_rating

FROM vehicles v

LEFT JOIN deliveries d
ON v.vehicle_id = d.vehicle_id

GROUP BY
    v.vehicle_id,
    v.vehicle_type,
    v.assigned_zone,
    v.maintenance_status

HAVING total_deliveries >= 3

ORDER BY
    failed_deliveries DESC,
    average_operational_cost DESC

")

vehicle_maintenance_analysis

    vehicle_id vehicle_type assigned_zone maintenance_status
1   V037       CargoVan     South         InRepair
2   V017       Hybrid       RiverSide     InRepair
3   V109       Hybrid       AIRPORT       InRepair
4   V002       EV           AIRPORT       InRepair
5   V057       EV           Riverside     InRepair
6   V011       Diesel       Riverside     InRepair
7   V108       Diesel       AIRPORT       InRepair
8   V072       CargoVan     AIRPORT       InRepair
9   V092       Hybrid       East          InRepair
10  V027       Diesel       SOUTH         InRepair
11  V096       CargoVan     East          InRepair
12  V114       Hybrid       North         Active
13  V042       EV           East          InRepair
14  V070       CargoVan     North         InRepair
15  V036       Diesel       North         InRepair
16  V005       CargoVan     West          Active
17  V103       Hybrid       North         InRepair
18  V062       Hybrid       North         Active
19  V030       CargoVan     North         Active
20  V088       Diesel       north         InRepair
21  V090       Hybrid       WEST          InRepair
22  V100       CargoVan     East          Active
23  V112       EV           South         InRepair
24  V118       Diesel       Riverside     Active
25  V069       Hybrid       CENTRAL       Active
26  V094       CargoVan     CENTRAL       Scheduled
27  V061       Diesel       South         Active
28  V007       Diesel       AIRPORT       Active
29  V110       EV           East          Active
30  V026       CargoVan     Riverside     InRepair
⋮   ⋮          ⋮            ⋮             ⋮
88  V040       EV           CENTRAL       Active
89  V085       CargoVan     SOUTH         Active
90  V067       Hybrid       Ctr           Active
91  V019       Diesel       SOUTH         Scheduled
92  V102       EV           West          Active
93  V047       EV           Ctr           Scheduled
94  V033       EV           AIRPORT       InRepair
95  V081       EV           West          Active
96  V001       EV           North         Active
97  V014       EV           AIRPORT       Scheduled
98  V087       Hybrid       AIRPORT       Active
99  V025       Diesel       AIRPORT       Active
100 V086       EV           CENTRAL       Scheduled
101 V082       EV           Ctr           Active
102 V022       Hybrid       South         Scheduled
103 V065       EV           West          Active
104 V013       CargoVan     WEST          Scheduled
105 V099       Hybrid       SOUTH         Active
106 V104       EV           EAST          Active
107 V048       Diesel       Central       Active
108 V115       Diesel       South         Active
109 V045       EV           EAST          Active
110 V009       CargoVan     South         Active
111 V049       Diesel       East          Active
112 V066       Hybrid       NORTH         Scheduled
113 V098       Diesel       WEST          Active
114 V028       EV           East          Active
115 V111       EV           WEST          Active
116 V089       CargoVan     CENTRAL       InRepair
117 V071       EV           West          Scheduled
    average_battery_health average_odometer_km total_deliveries
1    56.6                   52146               7
2    82.4                  169703              12
3    60.6                  193552              11
4    67.9                  159368               8
5    76.0                  160770               8
6    74.1                   43518               3
7    54.6                  141290               9
8    78.1                   89109               9
9    80.5                   36143               8
10   78.6                   51052              12
11   85.1                  193315               6
12   90.0                   84649              17
13   80.5                  215870              13
14   62.6                   39859               6
15   90.4                  215767               8
16   58.6                  146638              13
17  100.0                  181609               8
18   89.9                  113343               8
19   78.0                  134360              15
20   80.3                   50427              13
21   93.8                   98472              11
22   60.1                   31876              10
23   94.1                   19121               7
24   78.0                  145165               6
25   71.4                  187158               9
26   65.9                  159262              11
27   60.3                  126438               8
28   68.6                   78468               9
29   85.1                   63717               9
30   78.7                  200276               6
⋮   ⋮                      ⋮                   ⋮
88   90.0                  133770               7
89   87.3                  145652               9
90   57.3                  176145               9
91   70.4                  151460               3
92   77.0                  198326               7
93   93.7                  134347              17
94   78.6                   55241               4
95   86.6                  165481               9
96   71.8                   56928              10
97  100.0                  206339               7
98   49.7                  116811               5
99   42.0                   52074               6
100  82.8                   42307              11
101  81.2                   81518              11
102  89.6                   44499              11
103  84.3                  217057              11
104  68.3                  153106              10
105  65.8                   92896              13
106  73.9                   91441               4
107  76.1                   87659               6
108  57.9                   85919               5
109  88.0                  190688               9
110  68.8                  156687               9
111  55.9                   15278               6
112  77.7                   98535               9
113  69.7                   73011              15
114  75.4                  149698               5
115  66.3                  208147               7
116  93.6                  136082               3
117  73.8                  195310               7
    failed_deliveries average_operational_cost average_customer_rating
1   5                 14.63                    2.63
2   5                 12.29                    3.44
3   5                 12.13                    3.24
4   4                 15.16                    3.97
5   4                 10.95                    3.25
6   3                 17.93                    2.85
7   3                 14.40                    3.29
8   3                 13.60                    3.91
9   3                 13.49                    4.24
10  3                 13.44                    4.09
11  3                 12.82                    2.54
12  3                 12.72                    3.77
13  3                 12.33                    3.73
14  3                 12.17                    3.60
15  3                 11.62                    3.42
16  2                 15.47                    4.06
17  2                 14.84                    3.63
18  2                 14.71                    3.08
19  2                 13.74                    3.62
20  2                 13.56                    3.68
21  2                 13.01                    4.08
22  2                 12.99                    3.65
23  2                 12.91                    3.81
24  2                 12.88                    3.65
25  2                 12.86                    3.42
26  2                 12.74                    3.71
27  2                 12.41                    3.70
28  2                 12.22                    4.35
29  2                 11.58                    3.80
30  2                 11.57                    3.24
⋮   ⋮                 ⋮                        ⋮
88  0                 14.04                    3.76
89  0                 13.82                    3.96
90  0                 13.66                    3.83
91  0                 13.61                    4.17
92  0                 13.51                    3.93
93  0                 13.50                    3.90
94  0                 13.19                    3.10
95  0                 13.06                    3.76
96  0                 12.94                    3.82
97  0                 12.73                    4.14
98  0                 12.47                    4.67
99  0                 12.26                    4.24
100 0                 12.25                    4.00
101 0                 12.03                    4.06
102 0                 11.95                    3.59
103 0                 11.95                    4.56
104 0                 11.90                    4.11
105 0                 11.89                    3.86
106 0                 11.72                    4.07
107 0                 11.57                    4.27
108 0                 11.53                    4.28
109 0                 11.45                    4.21
110 0                 11.32                    4.16
111 0                 11.22                    4.12
112 0                 11.22                    4.21
113 0                 11.11                    4.04
114 0                 11.02                    3.37
115 0                 10.93                    4.00
116 0                 10.69                    3.60
117 0                  9.48                    4.22

In [ ]:
app_performance_analysis <- sqldf("

SELECT

    a.device_type,
    a.zone_context,
    a.event_type,

    COUNT(a.event_id) AS total_events,

    ROUND(
        AVG(a.api_latency_ms),
        2
    ) AS average_api_latency,

    SUM(
        CASE
            WHEN a.success_flag = 1
            THEN 1
            ELSE 0
        END
    ) AS successful_events,

    SUM(
        CASE
            WHEN a.success_flag = 0
            THEN 1
            ELSE 0
        END
    ) AS failed_events,

    ROUND(
        AVG(c.app_engagement_score),
        2
    ) AS average_engagement_score

FROM app_events a

LEFT JOIN customers c
ON a.customer_id = c.customer_id

GROUP BY
    a.device_type,
    a.zone_context,
    a.event_type

HAVING total_events >= 5

ORDER BY
    average_api_latency DESC,
    failed_events DESC

")

app_performance_analysis

   device_type zone_context event_type                  total_events
1  iOS         Airport      search_route                 7
2  Android     Ctr          chat_opened                  6
3  Android     South        payment_retry                6
4  Android     EAST         eta_refresh                  5
5  iOS         EAST         search_route                 5
6  Android     Ctr          eta_refresh                  7
7  Android     SOUTH        search_route                10
8  iOS         AIRPORT      track_order                  6
9  Android     Riverside    track_order                  8
10 iOS         East         track_order                  7
11 Android     RiverSide    eta_refresh                  6
12 Android     East         track_order                  8
13 Android     WEST         track_order                  9
14 iOS         Riverside    delivery_instruction_update  5
15 Android     Ctr          search_route                 6
16 iOS         RiverSide    payment_retry                5
17 iOS         WEST         eta_refresh                  6
18 Android     WEST         eta_refresh                  6
19 Android     NORTH        track_order                  5
20 Android     South        search_route                 7
21 Android     East         delivery_instruction_update  8
22 iOS         SOUTH        chat_opened                  5
23 Android     WEST         chat_opened                  6
   average_api_latency successful_events failed_events average_engagement_score
1  641.71               7                0             58.91
2  587.33               6                0             57.92
3  577.00               3                3             70.63
4  569.40               5                0             50.10
5  561.60               5                0             54.50
6  534.43               7                0             64.71
7  526.20              10                0             64.56
8  519.00               6                0             67.45
9  491.38               8                0             60.70
10 453.86               7                0             64.90
11 443.00               6                0             47.90
12 422.63               8                0             51.35
13 415.22               9                0             61.29
14 406.40               5                0             53.72
15 406.17               6                0             60.08
16 401.60               4                1             50.44
17 394.83               6                0             62.77
18 368.17               6                0             61.72
19 358.60               5                0             55.92
20 315.57               7                0             48.19
21 314.50               8                0             58.65
22 299.20               5                0             40.14
23 274.50               6                0             61.27

In [ ]:
optimized_delivery_query <- sqldf("

SELECT

    delivery_status,

    COUNT(delivery_id) AS total_deliveries,

    ROUND(
        AVG(route_distance_km),
        2
    ) AS average_route_distance,

    ROUND(
        AVG(fuel_or_charge_cost),
        2
    ) AS average_operational_cost

FROM deliveries

WHERE route_distance_km > 5

GROUP BY delivery_status

ORDER BY total_deliveries DESC

")

optimized_delivery_query

  delivery_status total_deliveries average_route_distance
1 OnTime          568              14.68
2 Delayed         183              15.90
3 Failed          125              14.00
  average_operational_cost
1 12.96
2 13.31
3 13.32